com.farao_community.farao.swe.api.exception.SweInvalidDataException#instance-init#